### ISSUE TITLE
Use Redirection URL on user confirmation

### ISSUE THREAD

**Issue by grillonbleu** [hrimhari/moodle-auth_loginlogoutredir#9]
When email-based self-registration is enabled, email confirmation effectively incurs a login which bypasses this plugin’s login redirection. I’d like to suggest that the "Continue" button on the screen following the email confirmation points to the login redirection URL instead of the default landing page after login.

If the maintainer agrees with this feature, I’d be glad to prepare a pull request.

**Comment by hrimhari** [comment]
Sure, go for it!

**Comment by hrimhari** [comment]
Thank you, I released the.new version with your change.
